services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:mysql://mysql:3306/study
      DB_USERNAME: study
      DB_PASSWORD: study
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  mysql:
    image: mysql
    container_name: study-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: study
      MYSQL_USER: study
      MYSQL_PASSWORD: study
    ports:
      - "3307:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  redis:
    image: redis:7.4-alpine
    container_name: study-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  mysql-data:
  redis-data:

