spring:
  application:
    name: flywayredis

  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user

jwt:
  issuer: flywayredis
  access-token-expiration: 30m
  refresh-token-expiration: 14d
  secret: ${JWT_SECRET}
